### ISSUE TITLE
Runner GUI: Reload should reload the suite

### ISSUE THREAD

**Issue by ghost** [kyleburton/transition.js#10]
The URI for the suite.js file should be registered with the Runner and the Runner should load it at 'init' time.  Then the Runner will be able to reload the suite when the "Reload" button is clicked.

When this change is made, the Runner will have to keep track of the current test, refresh the drop-down and set the selected item.

This will allow new tests to be added to the suite.js file w/o having to refresh the browser, aiding in interactive development.

**Comment by kyleburton** [comment]
This feature is implemented.
