### ISSUE TITLE
Test Runner Log output on IE7

### ISSUE THREAD

**Issue by ghost** [kyleburton/transition.js#11]
The pre block for the output log is printing log statements all on one line, even though there is a newline at the end of each statement.  Perhaps the output lot should become a div and individual lines paragraphs?  Regardless, this makes using the Runner in IE difficult.

**Comment by kyleburton** [comment]
The log entries are now all divs containing 2 spans.  Please test with IE7, if the issue remains, open another bug and it can be addressed via CSS.
