### ISSUE TITLE
Feature Request: Default behavior for newState().to()

### ISSUE THREAD

**Issue by ghost** [kyleburton/transition.js#18]
If the predicate is a string treat it as a jQuery selector an assume it's a call to elementExists_

Currently:

 19             this.newState('doLogin', 'doLogin')
 20                 .to('clickMyAccount', this.elementExists_('article.content_item')),

Proposed Change:

 19             this.newState('doLogin', 'doLogin')
 20                 .to('clickMyAccount', 'article.content_item'),

**Comment by kyleburton** [comment]
Addendum: if the string form identifies a function on the test, call it, otherwise attempt it as a jQuery selector.

**Comment by ghost** [comment]
This has been implemented.
